export class AudioEngine{
  constructor(){this.ctx=null;this.master=null;this.music=null;this.effects=null;this.timer=null;this.step=0;this.muted=localStorage.getItem('turkish-blocks-muted')==='1'}
  start(){if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.ctx=new AC;this.master=this.ctx.createGain();this.music=this.ctx.createGain();this.effects=this.ctx.createGain();this.master.gain.value=this.muted?0:.7;this.music.gain.value=.16;this.effects.gain.value=.38;this.music.connect(this.master);this.effects.connect(this.master);this.master.connect(this.ctx.destination);this.timer=setInterval(()=>this.musicStep(),180)}if(this.ctx.state==='suspended')this.ctx.resume()}
  tone(freq,duration=.12,type='sine',volume=.18,when=0,bus=this.effects){if(!this.ctx||this.muted)return;const now=this.ctx.currentTime+when,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);g.gain.setValueAtTime(.001,now);g.gain.exponentialRampToValueAtTime(volume,now+.015);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g);g.connect(bus);o.start(now);o.stop(now+duration+.03)}
  musicStep(){if(!this.ctx||this.muted)return;const melody=[523,659,784,659,587,698,880,698,659,784,988,784,587,698,880,784];const bass=[262,262,294,294,330,330,294,294];const i=this.step++;this.tone(melody[i%melody.length],.15,'triangle',.13,0,this.music);if(i%2===0)this.tone(bass[Math.floor(i/2)%bass.length],.3,'sine',.07,0,this.music)}
  play(name){const map={tap:[620,.07,'sine'],slide:[760,.05,'triangle'],drop:[260,.16,'sine'],clear:[880,.22,'triangle'],spawn:[520,.16,'triangle'],gain:[1040,.24,'sine'],use:[700,.18,'square'],over:[180,.5,'sawtooth']};const v=map[name];if(!v)return;this.tone(v[0],v[1],v[2]);if(name==='clear'||name==='gain')this.tone(v[0]*1.5,v[1],v[2],.12,.07)}
  pauseMusic(paused){if(this.ctx&&this.music)this.music.gain.setTargetAtTime(paused?0:.16,this.ctx.currentTime,.05)}
  toggle(){this.start();this.muted=!this.muted;this.master.gain.value=this.muted?0:.7;localStorage.setItem('turkish-blocks-muted',this.muted?'1':'0');return this.muted}
}
