import {Board,COLS,ROWS,COLORS} from './core.mjs?v=20260910-3';
import {AudioEngine} from './audio.mjs?v=20260910-2';
import {TOOL_DEFS as TOOLS,decorateBatch} from './items.mjs?v=20260910-3';
import {advanceCombo,comboMultiplier} from './combo.mjs?v=20260910-2';
import {createDifficultyState,planGenerationEvent} from './difficulty.mjs?v=20260910-1';

const $=id=>document.getElementById(id);
const ui={menu:$('menu'),game:$('game'),pause:$('pauseModal'),over:$('gameOverModal'),canvas:$('board'),score:$('score'),lines:$('lines'),combo:$('comboBadge'),hintTitle:$('hintTitle'),hintText:$('hintText'),itemBar:$('itemBar'),itemActions:$('itemActions'),useItem:$('useItemButton'),toast:$('toast'),audio:$('audioButton')};
const ctx=ui.canvas.getContext('2d'),audio=new AudioEngine();
const counts={move:$('itemMoveCount'),single:$('itemSingleCount'),row:$('itemRowCount'),color:$('itemColorCount')};
let board=new Board(),mode='normal',selected=null,dragStart=null,dragGhost=null,startCol=0,score=0,lines=0,combo=0,turnScoreBase=0,turnCleared=false,comboTimer=null,startedAt=0,paused=false,busy=false,nextBatches=[],difficultyState=createDifficultyState(),difficultyLevel=0,visualRows=null,visualAlpha=null,clearRows=null,clearProgress=0,inventory={move:0,single:0,row:0,color:0},noItemBatches=0,selectedTool=null,itemAim=null,itemDrag=null,moveAimVisual=null,toastTimer=null;

function getClientPoint(e){
  if(e.touches?.length)return {clientX:e.touches[0].clientX,clientY:e.touches[0].clientY,pointerId:e.touches[0].identifier ?? 0};
  if(e.changedTouches?.length)return {clientX:e.changedTouches[0].clientX,clientY:e.changedTouches[0].clientY,pointerId:e.changedTouches[0].identifier ?? 0};
  return {clientX:e.clientX,clientY:e.clientY,pointerId:e.pointerId??0};
}

function show(el,on){if(el)el.classList.toggle('hidden',!on)}
function toast(text){clearTimeout(toastTimer);ui.toast.textContent=text;show(ui.toast,true);toastTimer=setTimeout(()=>show(ui.toast,false),1500)}
function resize(){const box=ui.canvas.getBoundingClientRect();if(!box.width||!box.height)return;const dpr=Math.min(devicePixelRatio||1,2);ui.canvas.width=Math.round(box.width*dpr);ui.canvas.height=Math.round(box.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function metrics(){const w=ui.canvas.clientWidth,h=ui.canvas.clientHeight;return{w,h,cell:w/COLS,rowH:h/ROWS}}
function roundRect(x,y,w,h,r,fill,stroke=null,alpha=1,dash=[],shadow=false){ctx.save();ctx.globalAlpha=alpha;if(shadow){ctx.shadowColor='#74a8a64d';ctx.shadowBlur=4;ctx.shadowOffsetY=2}ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.shadowColor='transparent';ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.setLineDash(dash);ctx.stroke()}ctx.restore()}
function itemLanding(slider,row,col){const map=board.cells(slider.id);while(row<ROWS-1){let free=true;for(let c=col;c<col+slider.length;c++)if(map[row+1][c])free=false;if(!free)break;row++}return row}
function draw(){if(!ui.canvas.width)return;const m=metrics();ctx.clearRect(0,0,m.w,m.h);ctx.fillStyle='#fffdf7';ctx.fillRect(0,0,m.w,m.h);ctx.strokeStyle='#b7ddd8aa';ctx.lineWidth=1;for(let c=1;c<COLS;c++){ctx.beginPath();ctx.moveTo(c*m.cell,0);ctx.lineTo(c*m.cell,m.h);ctx.stroke()}for(let r=1;r<ROWS;r++){ctx.beginPath();ctx.moveTo(0,r*m.rowH);ctx.lineTo(m.w,r*m.rowH);ctx.stroke()}
  if(itemAim?.type==='row'){ctx.fillStyle='#ffcf7370';ctx.fillRect(0,itemAim.row*m.rowH,m.w,m.rowH)}
  if(dragGhost){const x=dragGhost.col*m.cell+3,y=dragGhost.row*m.rowH+3,w=dragGhost.length*m.cell-6,h=m.rowH-6;roundRect(x,y,w,h,8,'#fff0','#72b8b0',.82,[7,5])}
  for(const s of board.sliders){const row=visualRows?.get(s.id)??s.row;if(row<-.9)continue;const x=s.col*m.cell,y=row*m.rowH,w=s.length*m.cell,h=m.rowH,alpha=visualAlpha?.get(s.id)??1;let marked=false;if(selectedTool&&itemAim){if(itemAim.sliderId===s.id)marked=true;if(selectedTool==='color'&&itemAim.colorId===s.colorId)marked=true;if(selectedTool==='row'&&itemAim.row===s.row)marked=true}ctx.save();roundRect(x,y,w,h,6,COLORS[s.colorId],'#fffdf7',alpha,[],true);if((selected?.id===s.id&&!busy)||marked)roundRect(x+2,y+2,w-4,h-4,5,'#fff8b955','#fff7a8',alpha,[5,3]);if(s.itemType){ctx.globalAlpha=alpha;ctx.fillStyle='#416f72';ctx.font=`bold ${Math.max(13,m.rowH*.38)}px sans-serif`;ctx.textAlign='right';ctx.textBaseline='top';ctx.fillText(TOOLS[s.itemType].icon,x+w-5,y+3)}ctx.restore()}
  if(selectedTool==='move'&&itemAim?.type==='move'){const s=board.sliders.find(x=>x.id===itemAim.sliderId);if(s){if(!moveAimVisual){moveAimVisual={col:itemAim.col,row:itemAim.row};}else{moveAimVisual.col+= (itemAim.col-moveAimVisual.col)*0.28;moveAimVisual.row+= (itemAim.row-moveAimVisual.row)*0.28}const visCol=Math.round(moveAimVisual.col),visRow=Math.round(moveAimVisual.row);const x=visCol*m.cell,y=visRow*m.rowH,w=s.length*m.cell,h=m.rowH;const baseAlpha=itemAim.valid?0.22:0.28;const dash=itemAim.valid?[6,4]:[10,6];const stroke=itemAim.valid?'#5aaea5':'#ff6b6b';const fill=itemAim.valid?'#5aaea5':'#ff8a8a';const pulse=itemAim.valid?(0.2+0.08*Math.sin(performance.now()/120)):0.18;roundRect(x,y,w,h,6,fill,stroke,itemAim.valid?(0.45+pulse):baseAlpha,dash);if(!itemAim.valid){roundRect(x,y,w,h,6,fill,stroke,Math.min(0.55,baseAlpha+0.2),[8,4])}const landing=itemLanding(s,visRow,visCol);if(itemAim.valid&&landing!==visRow)roundRect(x,landing*m.rowH,w,h,6,COLORS[s.colorId],stroke,.22,[5,4])}}
  if(clearRows){for(const row of clearRows){ctx.save();ctx.globalAlpha=Math.sin(clearProgress*Math.PI)*.65;ctx.fillStyle='#fff7b0';ctx.fillRect(0,row*m.rowH,m.w,m.rowH);ctx.restore()}}
}
function cellAt(e){const rect=ui.canvas.getBoundingClientRect(),m=metrics();return{col:Math.floor((e.clientX-rect.left)/m.cell),row:Math.floor((e.clientY-rect.top)/m.rowH)}}
function sliderAt(e){const p=cellAt(e);return board.sliders.find(s=>s.row===p.row&&p.col>=s.col&&p.col<s.col+s.length)}
function select(s){if(busy||paused)return;selected=s;ui.hintTitle.textContent=s?'已选择滑块 · 左右拖动':'选择滑块 · 左右拖动';draw()}
function makeGenerationEvent(announce=false){const plan=planGenerationEvent(board,score,difficultyState);if(announce&&plan.level>difficultyLevel){toast(`难度提升 · ${plan.name}`);audio.play('gain')}difficultyLevel=plan.level;if(mode==='items'){const pieces=plan.batches.flat();const result=decorateBatch(pieces,noItemBatches);noItemBatches=result.noItemBatches}return plan.batches}
function renderPreview(){const el=$('nextBatch'),double=nextBatches.length===2;el.replaceChildren();el.classList.toggle('double',double);el.parentElement.classList.toggle('double',double);for(let row=0;row<nextBatches.length;row++)for(const p of nextBatches[row]){const piece=document.createElement('i');piece.className='next-piece';piece.style.gridColumn=`${p.col+1} / span ${p.length}`;piece.style.gridRow=String(row+1);piece.style.background=COLORS[p.colorId];piece.title=`长度 ${p.length}${p.itemType?' · '+TOOLS[p.itemType].name:''}`;if(p.itemType)piece.textContent=TOOLS[p.itemType].icon;el.appendChild(piece)}}
function renderInventory(){for(const type of Object.keys(TOOLS)){counts[type].textContent=`${inventory[type]}/2`;const button=ui.itemBar.querySelector(`[data-tool="${type}"]`);button.disabled=busy||inventory[type]===0;button.classList.toggle('active',selectedTool===type)}ui.useItem.disabled=!itemAim?.valid||busy}
function collectItems(sliders){for(const s of sliders){if(!s.itemType)continue;if(inventory[s.itemType]<2){inventory[s.itemType]++;toast(`获得 ${TOOLS[s.itemType].name}`)}else toast(`${TOOLS[s.itemType].name} 已溢出`);audio.play('gain')}renderInventory()}
function tween(ms,update){return new Promise(resolve=>{const begin=performance.now();const frame=now=>{const raw=Math.min(1,(now-begin)/ms),t=1-Math.pow(1-raw,3);update(t,raw);draw();raw<1?requestAnimationFrame(frame):resolve()};requestAnimationFrame(frame)})}
async function animateRows(from,to,entering=new Set(),duration=260){visualRows=new Map();visualAlpha=new Map();await tween(duration,t=>{for(const s of board.sliders){const a=entering.has(s.id)?ROWS+.8:(from.get(s.id)??s.row),b=to.get(s.id)??s.row;visualRows.set(s.id,a+(b-a)*t);visualAlpha.set(s.id,entering.has(s.id)?Math.min(1,t*1.8):1)}});visualRows=null;visualAlpha=null;draw()}
async function removeSliders(ids,rows=[]){const removing=board.sliders.filter(s=>ids.has(s.id));clearRows=new Set(rows);visualAlpha=new Map(board.sliders.map(s=>[s.id,1]));audio.play('clear');await tween(360,(t,raw)=>{clearProgress=raw;for(const s of removing)visualAlpha.set(s.id,raw<.35?1:Math.max(0,1-(raw-.35)/.65))});board.sliders=board.sliders.filter(s=>!ids.has(s.id));visualAlpha=null;clearRows=null;clearProgress=0;collectItems(removing);draw();return removing}
function beginTurn(){turnScoreBase=0;turnCleared=false}
function markRowsCleared(count){turnCleared=true;combo=advanceCombo(combo,count);if(count>0){clearTimeout(comboTimer);show(ui.combo,false);ui.combo.textContent=`COMBO ×${combo}`;void ui.combo.offsetWidth;show(ui.combo,true);comboTimer=setTimeout(()=>show(ui.combo,false),900)}}
function applyClear(total,chains){if(total){lines+=total;turnScoreBase+=total*100*Math.max(1,chains);ui.lines.textContent=lines}}
function finishCombo(){if(turnCleared){score+=Math.round(turnScoreBase*comboMultiplier(combo));ui.score.textContent=score}else{combo=advanceCombo(combo,0);clearTimeout(comboTimer);show(ui.combo,false)}}
async function settleAfterToolAction(){await resolveUntilStable();finishCombo();if(board.isGameOver()){finish();}else{selected=null;ui.hintTitle.textContent='选择滑块 · 左右拖动';renderInventory();}}
async function animateSettleAll(){const before=new Map(board.sliders.map(s=>[s.id,s.row]));board.settleAll();const after=new Map(board.sliders.map(s=>[s.id,s.row]));const moved=board.sliders.some(s=>before.get(s.id)!==after.get(s.id));if(moved){ui.hintTitle.textContent='连锁下落中…';audio.play('drop');await animateRows(before,after,new Set(),300)}return moved}
async function resolveUntilStable(){let total=0,chains=0;while(true){const full=board.fullRows();let cleared=false;if(full.length){markRowsCleared(full.length);chains++;total+=full.length;cleared=true;const rowSet=new Set(full),ids=new Set(board.sliders.filter(s=>rowSet.has(s.row)).map(s=>s.id));await removeSliders(ids,full)}const moved=await animateSettleAll();if(!cleared&&!moved)break}applyClear(total,chains);return{total,chains}}
async function spawnBatch(batch){const before=new Map(board.sliders.map(s=>[s.id,s.row]));board.liftBottomRow();const lifted=new Map(board.sliders.map(s=>[s.id,s.row]));await animateRows(before,lifted,new Set(),250);const idsBefore=new Set(board.sliders.map(s=>s.id));board.addBatch(batch);const spawned=new Map(board.sliders.map(s=>[s.id,s.row])),entering=new Set(board.sliders.filter(s=>!idsBefore.has(s.id)).map(s=>s.id));audio.play('spawn');await animateRows(lifted,spawned,entering,300);await animateSettleAll();if(board.fullRows().length)await resolveUntilStable()}
async function spawnPreviewEvent(){const batches=nextBatches;nextBatches=[];renderPreview();for(const batch of batches)await spawnBatch(batch)}
async function finishTurn(){await spawnPreviewEvent();while(board.sliders.length===0){nextBatches=makeGenerationEvent();await spawnPreviewEvent()}finishCombo();if(board.isGameOver()){finish();return}nextBatches=makeGenerationEvent(true);renderPreview();selected=null;busy=false;ui.hintTitle.textContent='选择滑块 · 左右拖动';renderInventory()}
async function commit(){if(!selected||busy||selected.col===startCol)return;busy=true;beginTurn();renderInventory();const d=board.fallDistance(selected);if(d){const from=new Map([[selected.id,selected.row]]),target=selected.row+d;selected.row=target;audio.play('drop');await animateRows(from,new Map([[selected.id,target]]),new Set(),Math.min(700,360+d*90))}await resolveUntilStable();await finishTurn()}

function resetTool(){selectedTool=null;itemAim=null;selected=null;itemDrag=null;moveAimVisual=null;show(ui.itemActions,false);renderInventory();draw()}
function activateTool(type){if(busy||paused||inventory[type]<=0)return;audio.play('tap');selectedTool=type;itemAim=null;selected=null;show(ui.itemActions,true);toast(TOOLS[type].name);renderInventory();draw()}
function aimTool(e){const p=cellAt(e),s=sliderAt(e);if(selectedTool==='single'&&s)itemAim={type:'single',sliderId:s.id,valid:true};else if(selectedTool==='color'&&s)itemAim={type:'color',sliderId:s.id,colorId:s.colorId,valid:true};else if(selectedTool==='row')itemAim={type:'row',row:p.row,valid:board.sliders.some(x=>x.row===p.row)};audio.play('tap');renderInventory();draw()}
function updateMoveItemAim(e){if(!itemDrag)return;const slider=board.sliders.find(s=>s.id===itemDrag.sliderId);if(!slider)return;const p=cellAt(e);const col=Math.max(0,Math.min(COLS-slider.length,p.col));const row=Math.max(0,Math.min(ROWS-1,p.row));const valid=board.canPlace(slider,row,col)&&(row!==slider.row||col!==slider.col);itemAim={type:'move',sliderId:slider.id,row,col,valid};renderInventory();draw()}
function startMoveItemDrag(e){if(selectedTool!=='move'||busy||paused)return;const s=sliderAt(e);if(!s)return;itemDrag={id:s.id,sourceRow:s.row,sourceCol:s.col,pointerId:e.pointerId};selected=s;itemAim={type:'move',sliderId:s.id,row:s.row,col:s.col,valid:false};moveAimVisual={col:s.col,row:s.row};audio.play('tap');ui.canvas.setPointerCapture(e.pointerId);renderInventory();draw()}
function finishMoveItemDrag(e){if(!itemDrag)return;const source=board.sliders.find(x=>x.id===itemDrag.id);if(source&&itemAim?.type==='move'&&!itemAim.valid){const from={col:itemAim.col,row:itemAim.row},to={col:itemDrag.sourceCol,row:itemDrag.sourceRow};const start=performance.now();const dur=150;const animate=()=>{if(!itemAim||!itemDrag)return;const t=Math.min(1,(performance.now()-start)/dur);if(t>=1){moveAimVisual={col:to.col,row:to.row};itemAim={type:'move',sliderId:itemDrag.id,row:to.row,col:to.col,valid:false};selected=null;itemDrag=null;renderInventory();draw();return}const ease=t*t*(3-2*t);moveAimVisual={col:from.col+(to.col-from.col)*ease,row:from.row+(to.row-from.row)*ease};draw();requestAnimationFrame(animate)};animate()}else{itemDrag=null;selected=null;moveAimVisual=null;renderInventory();draw();}}
async function useItem(){if(!selectedTool||!itemAim?.valid||busy)return;const type=selectedTool;busy=true;inventory[type]--;renderInventory();audio.play('use');let used=false;try{if(type==='move'){const s=board.sliders.find(x=>x.id===itemAim.sliderId);if(!s){toast('移动目标无效，已取消');return}const from=new Map([[s.id,s.row]]);s.row=itemAim.row;s.col=itemAim.col;await animateRows(from,new Map([[s.id,s.row]]),new Set(),260);const d=board.fallDistance(s);if(d){const fallFrom=new Map([[s.id,s.row]]);s.row+=d;audio.play('drop');await animateRows(fallFrom,new Map([[s.id,s.row]]),new Set(),Math.min(650,300+d*75))}used=true}else{let targets=[];if(type==='single')targets=board.sliders.filter(s=>s.id===itemAim.sliderId);if(type==='row')targets=board.sliders.filter(s=>s.row===itemAim.row);if(type==='color')targets=board.sliders.filter(s=>s.colorId===itemAim.colorId);await removeSliders(new Set(targets.map(s=>s.id)),type==='row'?[itemAim.row]:[]);await animateSettleAll();used=true}}finally{if(!used){inventory[type]++;}selectedTool=null;itemAim=null;show(ui.itemActions,false);moveAimVisual=null;selected=null;if(!board.isGameOver()){await settleAfterToolAction();busy=false;renderInventory();}else{busy=true}}}

function start(chosenMode=mode){mode=chosenMode;board=new Board();board.seed();inventory={move:0,single:0,row:0,color:0};noItemBatches=0;difficultyState=createDifficultyState();difficultyLevel=0;selected=null;selectedTool=null;itemAim=null;itemDrag=null;moveAimVisual=null;score=0;lines=0;combo=0;turnScoreBase=0;turnCleared=false;nextBatches=makeGenerationEvent();clearTimeout(comboTimer);show(ui.combo,false);busy=false;paused=false;startedAt=Date.now();ui.score.textContent='0';ui.lines.textContent='0';ui.game.classList.toggle('items-mode',mode==='items');show(ui.menu,false);show(ui.game,true);show(ui.pause,false);show(ui.over,false);show(ui.itemBar,mode==='items');show(ui.itemActions,false);renderPreview();renderInventory();audio.start();audio.pauseMusic(false);ui.audio.textContent=audio.muted?'×':'♪';resize();requestAnimationFrame(resize)}
function home(){show(ui.menu,true);show(ui.game,false);show(ui.pause,false);show(ui.over,false);show(ui.itemActions,false);paused=false;busy=false;audio.pauseMusic(true);resetTool()}
function togglePause(on){if(!ui.game.classList.contains('hidden')&&!busy){paused=on;audio.pauseMusic(on);show(ui.pause,on)}}
function finish(){busy=true;audio.play('over');audio.pauseMusic(true);const seconds=Math.floor((Date.now()-startedAt)/1000),key=`turkish-blocks-best-${mode}`,best=Math.max(score,Number(localStorage.getItem(key)||0));localStorage.setItem(key,String(best));$('finalScore').textContent=score;$('finalLines').textContent=lines;$('finalTime').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;$('bestScore').textContent=best;show(ui.over,true)}

function handlePointerDown(raw){const e={...raw,...getClientPoint(raw)};if(selectedTool){if(selectedTool==='move'){const proxy={clientX:e.clientX,clientY:e.clientY,pointerId:e.pointerId};startMoveItemDrag(proxy);return}aimTool({clientX:e.clientX,clientY:e.clientY});return}const proxy={clientX:e.clientX,clientY:e.clientY,pointerId:e.pointerId};const s=sliderAt(proxy);if(!s)return;select(s);audio.play('tap');dragStart=proxy.clientX;startCol=s.col;dragGhost={row:s.row,col:s.col,length:s.length};if(ui.canvas.setPointerCapture && e.pointerId!=null)ui.canvas.setPointerCapture(e.pointerId);draw()}
function handlePointerMove(raw){const e={...raw,...getClientPoint(raw)};if(selectedTool==='move'){updateMoveItemAim({clientX:e.clientX,clientY:e.clientY});return}else if(selectedTool||!selected||dragStart===null||busy)return;const m=metrics(),delta=Math.round((e.clientX-dragStart)/m.cell),target=Math.max(0,Math.min(COLS-selected.length,startCol+delta)),before=selected.col;selected.col=board.legalCol(selected,target);if(before!==selected.col)audio.play('slide');draw()}
function finishDrag(){if(selectedTool==='move'){finishMoveItemDrag();return}if(dragStart===null)return;dragStart=null;dragGhost=null;draw();commit()}
ui.canvas.addEventListener('pointerdown',handlePointerDown);ui.canvas.addEventListener('pointermove',handlePointerMove);ui.canvas.addEventListener('mousedown',handlePointerDown);ui.canvas.addEventListener('mousemove',handlePointerMove);
ui.canvas.addEventListener('pointerup',finishDrag);ui.canvas.addEventListener('pointercancel',finishDrag);ui.canvas.addEventListener('lostpointercapture',finishDrag);ui.canvas.addEventListener('mouseup',finishDrag);ui.canvas.addEventListener('mouseleave',finishDrag);
ui.canvas.addEventListener('touchstart',e=>{if(e.cancelable)e.preventDefault();handlePointerDown(e)});ui.canvas.addEventListener('touchmove',e=>{if(e.cancelable)e.preventDefault();handlePointerMove(e)});ui.canvas.addEventListener('touchend',finishDrag);ui.canvas.addEventListener('touchcancel',finishDrag);
$('normalModeButton').onclick=()=>start('normal');$('itemModeButton').onclick=()=>start('items');$('restartButton').onclick=()=>start(mode);$('homeButton').onclick=home;$('pauseHomeButton').onclick=home;$('pauseButton').onclick=()=>togglePause(true);$('resumeButton').onclick=()=>togglePause(false);$('cancelItemButton').onclick=resetTool;ui.useItem.onclick=useItem;for(const button of ui.itemBar.querySelectorAll('[data-tool]'))button.onclick=()=>activateTool(button.dataset.tool);ui.audio.onclick=()=>{ui.audio.textContent=audio.toggle()?'×':'♪'};
document.addEventListener('keydown',e=>{if(e.key==='Escape')selectedTool?resetTool():togglePause(!paused)});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!ui.game.classList.contains('hidden'))togglePause(true)});window.addEventListener('resize',resize);new ResizeObserver(resize).observe($('boardWrap'));show(ui.menu,true);show(ui.game,false);
